---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "crawler.fullname" . }}
  labels:
    app: search-engine
    component: crawler
    release: {{ .Release.Name }}
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: /
    prometheus.io/port: "8000"
spec:
  type: NodePort
  ports:
  - port: {{ .Values.service.externalPort }}
    protocol: TCP
    targetPort: {{ .Values.service.internalPort }}
  selector:
    app: search-engine
    component: crawler
    release: {{ .Release.Name }}

