#!/bin/sh
set -e

export DOMAIN=se-project.tk

cd infra

echo "alertmanager:
  ingress:
    hosts:
      - alertmanager.$DOMAIN

server:
  ingress:
    hosts:
      - monitoring.$DOMAIN
" > values-prometheus-ingress.yml

#sed -i "s/example.com/$DOMAIN/g" values-prometheus.yml
helm upgrade --install prometheus -f values-prometheus-ingress.yml  -f values-prometheus.yml stable/prometheus

echo "ingress:
  hosts:
    - monitoring.$DOMAIN
" > values-grafana-ingress.yml

#sed -i "s/example.com/$DOMAIN/g" values-grafana.yml
helm upgrade --install grafana -f values-grafana-ingress.yml  -f values-grafana.yml stable/grafana



echo "##########################################################################################################"
echo "##########################################################################################################"
echo "##########################################################################################################"
echo "##########################################################################################################"
echo "Grafana admin password:"
kubectl get secret --namespace default grafana -o jsonpath="{.data.admin-password}" | base64 --decode ; echo
echo "##########################################################################################################"
echo "##########################################################################################################"
echo "##########################################################################################################"
echo "##########################################################################################################"

