alertmanager:
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
    #   kubernetes.io/tls-acme: 'true'

alertmanagerFiles:
  alertmanager.yml:
    global:
      slack_api_url: 'https://hooks.slack.com/services/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'

    route:
      receiver: 'slack-notifications'

    receivers:
    - name: 'slack-notifications'
      slack_configs:
        - channel: '#pavel_lukin'

server:
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
    #   kubernetes.io/tls-acme: 'true'

serverFiles:
  alerting_rules.yml:
    groups:
      - name: alert.rules
        rules:
        - alert: InstanceDown
          expr: up == 1
          for: 1m
          labels:
            severity: page
          annotations:
            description: '{{ $labels.instance }} of job {{ $labels.job }} has been down for more than 1 minute'
            summary: 'Instance {{ $labels.instance }} down'
