---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}
  labels:
    app: search-engine
    component: mongodb
    release: {{ .Release.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: search-engine
      component: mongodb
      release: {{ .Release.Name }}
  template:
    metadata:
      name: mongodb
      labels:
        app: search-engine
        component: mongodb
        release: {{ .Release.Name }}
    spec:
      containers:
      - image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        name: mongodb
        ports:
        - containerPort: {{ .Values.service.internalPort }}
          name: mongodb
          protocol: TCP
